name: Count Signature Number
on: push

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup S.C.
        id: sc-dl
        run: |
          wget "https://github.com/LGBT-CN/signature-counter/releases/latest/download/signature-counter"
          chmod +x ./signature-counter
          chmod +w *
      - name: Run S.C.
        run: |
          ./signature-counter ./README.md
          rm -f ./signature-counter
      - name: Commit S.C.
        run: |
          git config user.name KevinZonda
          git config user.email 33132228+KevinZonda@users.noreply.github.com
          git add .
          git commit -m "S.C.: `date "+%Y-%m-%d %H:%M:%S UTC%:z"`" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
