name: Invite to Organisation
on:
  push:
    branches: master
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite
        uses: lekterable/inclusive-organization-action@v1.1.0
        with:
          organization: LGBT-CN
          team: Friends
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
